[package]
name = "lgsim"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.0" # The GUI library
egui = "0.24.0"

[profile.dev.package.'*']
opt-level = 3
